import type { Metadata } from "next";
import 'bootstrap-icons/font/bootstrap-icons.css';
import "../styles/globals.css"

export const metadata: Metadata = {
  title: "Indie Comic",
  description: "Generated by create next app",
};

export default function RootLayout({ children}: Readonly<{ children: React.ReactNode}>) {
  return (
    <html lang="en">
      <link rel="icon" href="images/icone.png" />
      <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet"></link>
      <body>
        {children}
      </body>
    </html>
  );
}
